[tool.poetry]
name = "python-tutorial"
version = "0.1.0"
description = ""
authors = ["ray <wuhaohsiang1992@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ipython = "^8.2.0"
ipykernel = "^6.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
